-- Step 1: Database Schema for Auction Website
-- This creates all the tables needed for the auction system
-- The schema is in Third Normal Form (3NF)

-- Drop tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS auctions;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

-- Create users table to store user account information
CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,  -- unique ID for each user
    email VARCHAR(255) NOT NULL UNIQUE,      -- user's email (also username)
    password VARCHAR(255) NOT NULL,          -- user's hashed password
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- when account was created
);

-- Create sessions table for server-side session management
-- Replaces client-side cookie expiration with MySQL-tracked activity
CREATE TABLE sessions (
    session_id CHAR(36) PRIMARY KEY,              -- UUID generated by MySQL UUID()
    user_id INT NOT NULL,                          -- which user owns this session
    last_activity TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- last request time
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,              -- when session started
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Create auctions table to store items being sold
CREATE TABLE auctions (
    auction_id INT AUTO_INCREMENT PRIMARY KEY,  -- unique ID for each auction
    seller_id INT NOT NULL,                     -- who is selling the item
    item_description TEXT NOT NULL,             -- description of the item
    starting_bid DECIMAL(10, 2) NOT NULL,       -- minimum bid amount
    current_bid DECIMAL(10, 2) NOT NULL,        -- current highest bid
    start_time TIMESTAMP NOT NULL,              -- when auction started
    end_time TIMESTAMP NOT NULL,                -- when auction ends (start + 168 hours)
    is_closed BOOLEAN DEFAULT FALSE,            -- whether auction has ended
    winner_id INT DEFAULT NULL,                 -- who won the auction (NULL if no bids)
    FOREIGN KEY (seller_id) REFERENCES users(user_id),  -- link to users table
    FOREIGN KEY (winner_id) REFERENCES users(user_id)   -- link to users table
);

-- Create bids table to store all bids placed on auctions
CREATE TABLE bids (
    bid_id INT AUTO_INCREMENT PRIMARY KEY,      -- unique ID for each bid
    auction_id INT NOT NULL,                    -- which auction this bid is for
    bidder_id INT NOT NULL,                     -- who placed the bid
    bid_amount DECIMAL(10, 2) NOT NULL,         -- how much they bid
    bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- when bid was placed
    FOREIGN KEY (auction_id) REFERENCES auctions(auction_id),  -- link to auctions table
    FOREIGN KEY (bidder_id) REFERENCES users(user_id)          -- link to users table
);

-- Create index on email for faster login lookups
CREATE INDEX idx_email ON users(email);

-- Create index on session user_id for faster session lookups
CREATE INDEX idx_session_user ON sessions(user_id);

-- Create index on auction end time for faster sorting
CREATE INDEX idx_end_time ON auctions(end_time);

-- Create index on auction seller for faster transaction lookups
CREATE INDEX idx_seller ON auctions(seller_id);

-- Create index on bids for faster transaction history
CREATE INDEX idx_bidder ON bids(bidder_id);
CREATE INDEX idx_auction_bids ON bids(auction_id);