USE cs370_section2_allindragons;
DROP VIEW IF EXISTS v_user_purchases;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS auctions;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;